version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 216989130794.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t website-demo .
      - docker tag website-demo:latest 216989130794.dkr.ecr.us-east-1.amazonaws.com/website-demo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 216989130794.dkr.ecr.us-east-1.amazonaws.com/website-demo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"website-demo","imageUri":"216989130794.dkr.ecr.us-east-1.amazonaws.com/website-demo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - demo- '**/*'
